#!/bin/bash

#####################################################################################
# Copyright Glyfo Company. 2020. All Rights Reserved.                               #
# Apache License, Version 2.0. See LICENSE file in the project root for details.    #
# name    : Command Line Tool to deploy Smart Contract on Solana                    #
# website : glyfo.com                                                               #
# support : hello@glyfo.com                                                         #
#####################################################################################

# ---------------------- TIPS -------------------------------
#   export PATH=$_path - variable _path is a global var 
#   echo $PWD          -  this is a bash session  
#   echo \$PWD         -  this is a container session 


SOLANA_VERSION=v1.9.5
ANCHOR_VERSION=v0.20.1
SOLANA_CHAIN="http://localhost:8899"
WALLET_FILE="/usr/local/solana/walletid.json" 


## ----------------------  GLOBAL --------------------------
_path="/usr/local/solana/bin:/usr/local/cargo/bin:/bin:/usr/bin:/root/.local/share/solana/install/active_release/bin"

b=$(tput bold)
n=$(tput sgr0)


## ----------------------  UTIL FUNCTION ---------------------

call2cmd () {
   docker exec -i solanaX /bin/bash -s <<EOF 
   export PATH=$_path
   $1
   exit
EOF
  
}

version () {
   echo "glyclt 0.0.1"
}

help () {
   echo "${n} Usage: ${b} glyclt ${n}

${b}+ setup${n}         : Handler Container to Compile & Install Software 
     + solana   : Compile & Install Solana Tools & Node into Container
     + anchor   : Compile & Install Anchor into Container
     + dev      : Install Node,NPM and Yarn into the Container
     + login    : Access to Container 
     + reset    : Restart Container ( Stop & Start ) 
     + delete   : Delete Container
${b}+ run${n}           : Running Solana Test Node inside Container 
${b}+ wallet${n}        : Handler Wallet 
     + create   : Create Wallet and Save Wallet into the Container
     + airdrop  : Add SOL to Wallet
     + balance  : Review Balance
${b}+ anchor${n}        : Solana FrameWork 
     + init     : Create Project Folder 
     + build    : Compile Program
     + deploy   : Deploy Program on Solana Test Node
     + test     : Running Test 
${n} "
 
}


## ----------------------  BEGIN SETUP --------------------------
if [ "$1" = "setup" ]
then
   case "$2" in 
   'solana')
   docker stop solanaX
   docker rm solanaX
   docker pull rust
   docker run  --name solanaX -v $(pwd):/usr/src -w /usr/src -id rust  tail -f /dev/null
   docker exec -i solanaX /bin/bash -s <<EOF
          echo '----------------------- Core Tool--------------------------' 
          uname -a
          apt-get -qq update 
          apt-get -qq upgrade 
          apt-get -qq install -y pkg-config build-essential libudev-dev libclang-dev net-tools --no-install-recommends apt-utils
          rustup component add rustfmt
          export PATH=$_path
          echo '----------------------- Core Tool Version --------------------------' 
          rustc -V 
          cargo -V
          git --version
          echo '----------------------- Building Solana ----------------------------'
          sleep 1
          cd /usr/local 
          git -c advice.detachedHead=false clone -b $SOLANA_VERSION  https://github.com/solana-labs/solana
          cd solana
          sed '7,13d' ./scripts/cargo-install-all.sh > ./scripts/cargo-install-all-fix.sh
          sed '6 a cargo=cargo' ./scripts/cargo-install-all-fix.sh > ./scripts/cargo-install-all-fix2.sh
          cat ./scripts/cargo-install-all-fix2.sh > ./scripts/cargo-install-all-fix.sh 
          rm  ./scripts/cargo-install-all-fix2.sh
          bash ./scripts/cargo-install-all-fix.sh --validator-only .
          cargo build --release --bin solana-test-validator
          cp /usr/local/solana/target/release/solana-test-validator /usr/local/solana/bin/
          export PATH="/usr/local/solana/bin:/bin:/usr/local/cargo/bin:/usr/bin:/root/.local/share/solana/install/active_release/bin"
          echo '----------------------- Solana Tool Version --------------------------' 
          solana -V
          solana-keygen --version
          solana-test-validator --version
          exit
EOF
   exit
;;
   'anchor')
   docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   cd /usr/local 
   echo '----------------------- Building Anchor --------------------'
   cargo install --git https://github.com/project-serum/anchor --tag $ANCHOR_VERSION anchor-cli  --locked
   exit
EOF
   exit
;;
   'dev')
    docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   echo '----------------------- Installing NPM --------------------'
   curl -fsSL https://deb.nodesource.com/setup_16.x | bash - > /dev/null
   apt-get -qq install -y nodejs
   npm install --global yarn
   node --version
   npm  --version 
   yarn --version
   exit
EOF
   exit
;;
   'login')
    docker exec -it solanaX /bin/bash 
    exit   
;;
   'release')
    docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   echo '----------------------- Release  --------------------'
   echo  "rustc          $(rustc -V |awk '{ print $2 }' )"
   echo  "cargo          $(cargo -V |awk '{ print $2 }' )"
   echo  "solana         $(solana -V |awk '{ print $2 }' )"
   echo  "solana-keygen  $(solana-keygen -V |awk '{ print $2 }' )"
   echo  "node           $(node --version |awk '{ print $1 }' )"  
   echo  "npm            $(npm --version |awk '{ print $1 }' )"  
   echo  "yarn           $(yarn --version |awk '{ print $1 }' )"  
   exit
EOF
   exit
;;
   *) 
   echo "${n} Usage: ${b} glyclt setup ${n}

  + solana   : Compile & Install Solana Tools & Node into Container
  + anchor   : Compile & Install Anchor into Container
  + dev      : Install Node,NPM and Yarn into the Container
  + login    : Access to Container 
  + reset    : Restart Container ( Stop & Start ) 
  + delete   : Delete Container
  "
  exit
;; 
esac
fi

## ----------------------  END SETUP ----------------------------

## ----------------------  BEGIN ANCHOR -------------------------

if [ "$1" = "anchor" ]
then
   case "$2" in 
   'init')
   call2cmd "anchor init hello"
   ;;
   'build')
   echo "Building Smart Contract .........."
   docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   export RUST_BACKTRACE=full
   cd counter
   cargo build-bpf 
   anchor idl parse -f src/lib.rs -o target/idl/rcp-mapping.json
   exit
EOF   
   exit
;;
   'deploy')
   echo "Deploy  .........."
   docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   cd counter
   solana program deploy -k /usr/local/solana/walletid.json  target/deploy/counter.so --url https://api.devnet.solana.com 
   exit
EOF
   exit
;;
   'reset')
    echo "Stop Container"
    docker stop  $(docker ps -a |grep solanaX |awk '{ print $1 }' )
    echo "Start Container"
    docker start $(docker ps -a |grep solanaX |awk '{ print $1 }' )
    exit
;;
'delete')
    echo "Delete Container Enviroment"
    docker stop solanaX
    docker rm solanaX
    exit
;;
esac
fi

## ----------------------  END ANCHOR -------------------------



## ----------------------  BEGIN WALLET -------------------------

if [ "$1" = "wallet" ]
then
   case "$2" in 
   'create')
   echo "Create Wallet .........."
   docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   echo "Wallet creation .........."
   solana config set --url $SOLANA_CHAIN
   solana-keygen new -f -s --no-bip39-passphrase --outfile $WALLET_FILE  
   echo '-----------------------Public Key ------------------------'
   solana-keygen pubkey $WALLET_FILE 
   echo '----------------------------------------------------------'
   echo '-----------------------Private Key -----------------------'
   cat $WALLET_FILE   
   echo ''
   echo '----------------------------------------------------------'
   exit
EOF
exit
;;
   'airdrop')
   echo "Airdrop Wallet .........."
   docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path 
   export pubkey=$(solana-keygen pubkey /usr/local/solana/walletid.json  )
   echo '----------------------------------------------------------'
   echo "Public Key:"
   printf '%s\n' "$(solana-keygen pubkey /usr/local/solana/walletid.json  )" 
   echo '----------------------------------------------------------'
   solana airdrop 5 $pubkey  walletid.json  --url http://localhost:8899
   exit
EOF
exit
;;
   'balance')
   echo "Airdrop Wallet .........."
   docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path 
   export pubkey=$(solana-keygen pubkey /usr/local/solana/walletid.json  )
   echo '----------------------------------------------------------'
   echo "Public Key:"
   printf '%s\n' "$(solana-keygen pubkey /usr/local/solana/walletid.json  )" 
   echo '----------------------------------------------------------'
   solana airdrop 5 $pubkey  walletid.json  --url http://localhost:8899
   exit
EOF
exit
;;
esac
fi

## ----------------------  END WALLET -------------------------

## ----------------------  MAIN  ------------------------------

case "$1" in
'run')
docker exec -i solanaX /bin/bash -s <<EOF 
   export PATH=$_path
   echo "Running Solana  Test Validator.........."
   cd /usr/local/solana
   nohup solana-test-validator > /dev/null 2>&1 &
   exit
EOF
exit
;;
'log')
docker exec -i solanaX /bin/bash -s <<EOF 
   export PATH=$_path
   netstat -an | grep LISTEN
   #tail -30 /usr/local/solana/test-ledger/validator.log
   exit
EOF
exit
;;
'info')
docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path
   solana program show --buffers --all --keypair /usr/local/solana/walletid.json   --url http://localhost:8899
   exit
EOF
exit
;;
'help')
help 
;; 
'version')
version 
;; 
*)
help 
;;
esac
