#!/bin/ksh

_path="/usr/local/solana/bin:/usr/local/cargo/bin:/bin:/usr/bin:/root/.local/share/solana/install/active_release/bin"

SOLANA_VERSION=v1.9.5
ANCHOR_VERSION=v0.20.1
SOLANA_CHAIN="http://localhost:8899"
WALLET_FILE="/usr/local/solana/walletid.json"

docker exec -i solanaX /bin/bash -s <<EOF
   export PATH=$_path 
   solana-keygen pubkey $WALLET_FILE | awk \
   -v wallet="${WALLET_FILE}"              \
   -v chain="${SOLANA_CHAIN}"              \
  '{ print "PUBKEY"; print $1 ; print ""; system("exec /usr/local/solana/bin/solana airdrop 5 " $1 wallet " --url " chain ) }'
   exit 
EOF
exit

